import mongoose, { Schema, type Document, type Model, type Types } from "mongoose";
import { TranscriptSource, VideoProcessingStatus } from "../enums.js";

export interface ICreatorVideo {
  creatorId: Types.ObjectId;
  channelId: string;

  youtubeVideoId: string;
  url: string;

  title: string;
  description?: string;

  publishedAt?: Date;
  durationSeconds: number;

  stats?: {
    viewCount?: number;
    likeCount?: number;
    commentCount?: number;
  };

  transcript: {
    available: boolean;
    language?: string;
    isAutoGenerated?: boolean;
    source?: TranscriptSource;
    fetchedAt?: Date;
    totalSeconds?: number;
    wordCount?: number;
  };

  selection: {
    selectedForPersona: boolean;
    reason?: string;
    rankScore?: number;
  };

  processing: {
    status: VideoProcessingStatus;
    error?: string;
  };
}

export interface ICreatorVideoDocument extends ICreatorVideo, Document {
  id: string;
  createdAt: Date;
  updatedAt: Date;
}

const creatorVideoSchema = new Schema<ICreatorVideoDocument>(
  {
    creatorId: {
      type: Schema.Types.ObjectId,
      ref: "Creator",
      required: true,
      index: true,
    },

    channelId: {
      type: String,
      required: true,
      trim: true,
    },

    youtubeVideoId: {
      type: String,
      required: true,
      trim: true,
    },

    url: {
      type: String,
      required: true,
      trim: true,
    },

    title: {
      type: String,
      required: true,
      trim: true,
    },

    description: String,

    publishedAt: Date,

    durationSeconds: {
      type: Number,
      required: true,
      min: 0,
    },

    stats: {
      viewCount: Number,
      likeCount: Number,
      commentCount: Number,
    },

    transcript: {
      available: {
        type: Boolean,
        default: false,
      },
      language: String,
      isAutoGenerated: Boolean,
      source: {
        type: String,
        enum: Object.values(TranscriptSource),
      },
      fetchedAt: Date,
      totalSeconds: Number,
      wordCount: Number,
    },

    selection: {
      selectedForPersona: {
        type: Boolean,
        default: false,
      },
      reason: String,
      rankScore: Number,
    },

    processing: {
      status: {
        type: String,
        enum: Object.values(VideoProcessingStatus),
        default: VideoProcessingStatus.PENDING,
      },
      error: String,
    },
  },
  { timestamps: true },
);

creatorVideoSchema.index(
  { creatorId: 1, youtubeVideoId: 1 },
  { unique: true },
);

creatorVideoSchema.index({ creatorId: 1, "stats.viewCount": -1 });
creatorVideoSchema.index({ creatorId: 1, durationSeconds: -1 });
creatorVideoSchema.index({ creatorId: 1, "selection.selectedForPersona": 1 });
creatorVideoSchema.index({ creatorId: 1, "processing.status": 1 });

export const CreatorVideo: Model<ICreatorVideoDocument> = mongoose.models.CreatorVideo ?? mongoose.model<ICreatorVideoDocument>("CreatorVideo", creatorVideoSchema);